MODEL:
  BERT_CKPT: "hfl/chinese-macbert-base"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.3 ]
  GPU_IDS: [ 0 ]
  #WEIGHTS: "output/macbert4csc/epoch=6-val_loss=0.07.ckpt"
  WEIGHTS: ""

DATASETS:
  TRAIN: "output/dev.json"
  VALID: "output/dev.json"
  TEST: "output/dev.json"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 32
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4


TEST:
  BATCH_SIZE: 32

TASK:
  NAME: "csc"

OUTPUT_DIR: "output/macbert4csc"
MODE: [ 'train', "test" ]
